version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: backend-web-simulation-conv-doanngoccuong:latest
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    container_name: websim-backend
    environment:
      - CORS_ORIGINS=http://localhost:25051,http://frontend:80

  frontend:
    build:
      context: ./frontend
    image: frontend-web-simulation-conv-doanngoccuong:latest
    ports:
      - "80:80"
    restart: unless-stopped
    container_name: websim-frontend
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=ws://localhost:8000

networks:
  default:
    name: web-simulation-conv-doanngoccuong 