version: '3.8'

# Thêm tên dự án rõ ràng để tránh xung đột
name: web-simulation-conversation

services:
  backend:
    build:
      context: ./backend
    image: backend-web-simulation-conv-doanngoccuong:latest
    ports:
      - "25050:25050"
    restart: unless-stopped
    container_name: websim-backend
    environment:
      - CORS_ORIGINS=http://localhost:25051,http://frontend:80,http://103.253.20.13:25051,http://103.253.20.13:9404
      - DOCKER=true
      - ENVIRONMENT=production
      - API_BASE_URL=http://103.253.20.13:9404
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - websim_logs:/app/logs
      - ./backend/.env:/app/.env
    networks:
      - web-simulation-network
    command: uvicorn main:app --host 0.0.0.0 --port 25050

    # Điều chỉnh healthcheck để dễ thở hơn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:25050/health", "||", "exit", "1"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 40s

  frontend:
    build:
      context: ./front-end-refactor
    image: frontend-web-simulation-conv-doanngoccuong:latest
    ports:
      - "25051:80"
    restart: unless-stopped
    container_name: websim-frontend
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://103.253.20.13:25050
    networks:
      - web-simulation-network
    # Điều chỉnh healthcheck
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80", "||", "exit", "1"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 20s

volumes:
  websim_logs:
    name: websim_logs  # Đặt tên cụ thể cho volume

networks:
  web-simulation-network:
    name: web-simulation-conv-doanngoccuong  # Giữ nguyên tên mạng đã định nghĩa
    driver: bridge


